%% Build Simulink Model for Audio Loopback Test
% This script creates a complete Simulink model for testing
% audio loopback with the RA8P1 board
%
% Run this script ONCE to create the model, then use the model

clear; clc; close all;

%% Configuration
modelName = 'RA8P1_AudioLoopback';
Fs = 48000;           % Sample rate
frameSize = 1024;     % Frame size
sineFreq = 1000;      % Test frequency
sineAmp = 0.5;        % Amplitude

% Audio device names
outputDev = 'Headphones (3- USB Audio Demonstration)';
inputDev = 'Microphone (3- USB Audio Demonstration)';

%% Close existing model
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist([modelName '.slx'], 'file')
    delete([modelName '.slx']);
end

%% Create new model
new_system(modelName);
open_system(modelName);

%% Set Solver Configuration
set_param(modelName, ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(frameSize/Fs), ...
    'StopTime', 'inf', ...
    'EnablePacing', 'on', ...
    'PacingRate', '1');

%% Add Signal Generation Block
add_block('dsp/Sources/Sine Wave', [modelName '/SineWave']);
set_param([modelName '/SineWave'], ...
    'Amplitude', num2str(sineAmp), ...
    'Frequency', num2str(sineFreq), ...
    'SampleMode', 'Discrete', ...
    'SampleTime', num2str(1/Fs), ...
    'SamplesPerFrame', num2str(frameSize), ...
    'OutputDataType', 'double', ...
    'Position', [50, 100, 100, 150]);

%% Add Audio Device Writer (TX to Board)
add_block('audio/Sources and Sinks/Audio Device Writer', [modelName '/AudioOut']);
set_param([modelName '/AudioOut'], ...
    'Device', outputDev, ...
    'SampleRate', num2str(Fs), ...
    'Position', [250, 100, 350, 150]);

%% Add Audio Device Reader (RX from Board)
add_block('audio/Sources and Sinks/Audio Device Reader', [modelName '/AudioIn']);
set_param([modelName '/AudioIn'], ...
    'Device', inputDev, ...
    'SampleRate', num2str(Fs), ...
    'SamplesPerFrame', num2str(frameSize), ...
    'NumChannels', '1', ...
    'OutputDataType', 'double', ...
    'Position', [50, 250, 150, 300]);

%% Add Terminator for AudioIn overflow output
add_block('simulink/Sinks/Terminator', [modelName '/Term1']);
set_param([modelName '/Term1'], 'Position', [200, 285, 220, 305]);

%% Add Spectrum Analyzers
% TX Spectrum
add_block('dsp/Sinks/Spectrum Analyzer', [modelName '/SpectrumTX']);
set_param([modelName '/SpectrumTX'], ...
    'SampleRate', num2str(Fs), ...
    'PlotAsTwoSidedSpectrum', 'off', ...
    'SpectrumType', 'Power density', ...
    'ViewType', 'Spectrum and spectrogram', ...
    'Position', [250, 30, 350, 80]);

% RX Spectrum
add_block('dsp/Sinks/Spectrum Analyzer', [modelName '/SpectrumRX']);
set_param([modelName '/SpectrumRX'], ...
    'SampleRate', num2str(Fs), ...
    'PlotAsTwoSidedSpectrum', 'off', ...
    'SpectrumType', 'Power density', ...
    'ViewType', 'Spectrum and spectrogram', ...
    'Position', [250, 330, 350, 380]);

%% Add Time Scope for Waveforms
add_block('simulink/Sinks/Scope', [modelName '/WaveformScope']);
set_param([modelName '/WaveformScope'], 'Position', [500, 170, 550, 220]);

% Configure scope for 2 inputs
scopeConfig = get_param([modelName '/WaveformScope'], 'ScopeConfiguration');
scopeConfig.NumInputPorts = '2';
scopeConfig.LayoutDimensions = [2 1];
set_param([modelName '/WaveformScope'], 'ScopeConfiguration', scopeConfig);

%% Add MATLAB Function Block for Latency Calculation
add_block('simulink/User-Defined Functions/MATLAB Function', [modelName '/LatencyCalc']);
set_param([modelName '/LatencyCalc'], 'Position', [400, 250, 500, 310]);

%% Add Display Blocks
add_block('simulink/Sinks/Display', [modelName '/LatencyDisplay']);
set_param([modelName '/LatencyDisplay'], ...
    'Format', 'short', ...
    'Position', [550, 250, 620, 280]);

add_block('simulink/Sinks/Display', [modelName '/CorrDisplay']);
set_param([modelName '/CorrDisplay'], ...
    'Format', 'short', ...
    'Position', [550, 290, 620, 320]);

%% Add Constant for Sample Rate
add_block('simulink/Sources/Constant', [modelName '/FsConst']);
set_param([modelName '/FsConst'], ...
    'Value', num2str(Fs), ...
    'Position', [300, 350, 340, 370]);

%% Connect Blocks
% Sine to Audio Out
add_line(modelName, 'SineWave/1', 'AudioOut/1', 'autorouting', 'smart');

% Sine to TX Spectrum
add_line(modelName, 'SineWave/1', 'SpectrumTX/1', 'autorouting', 'smart');

% Sine to Scope input 1
add_line(modelName, 'SineWave/1', 'WaveformScope/1', 'autorouting', 'smart');

% Audio In to RX Spectrum
add_line(modelName, 'AudioIn/1', 'SpectrumRX/1', 'autorouting', 'smart');

% Audio In to Scope input 2
add_line(modelName, 'AudioIn/1', 'WaveformScope/2', 'autorouting', 'smart');

% Audio In overflow to Terminator
add_line(modelName, 'AudioIn/2', 'Term1/1', 'autorouting', 'smart');

% Connections to Latency Calculator (will need manual setup for MATLAB Function)
add_line(modelName, 'SineWave/1', 'LatencyCalc/1', 'autorouting', 'smart');
add_line(modelName, 'AudioIn/1', 'LatencyCalc/2', 'autorouting', 'smart');
add_line(modelName, 'FsConst/1', 'LatencyCalc/3', 'autorouting', 'smart');

% Latency outputs to displays
add_line(modelName, 'LatencyCalc/1', 'LatencyDisplay/1', 'autorouting', 'smart');
add_line(modelName, 'LatencyCalc/2', 'CorrDisplay/1', 'autorouting', 'smart');

%% Save Model
save_system(modelName);

%% Create the MATLAB Function code file
latencyFcnCode = [...
'function [latency_ms, correlation] = fcn(tx_signal, rx_signal, Fs)' newline ...
'%#codegen' newline ...
'% Latency Calculator using Cross-Correlation' newline ...
'% Inputs:' newline ...
'%   tx_signal - Transmitted signal (frame)' newline ...
'%   rx_signal - Received signal (frame)' newline ...
'%   Fs        - Sample rate' newline ...
'% Outputs:' newline ...
'%   latency_ms  - Measured latency in milliseconds' newline ...
'%   correlation - Normalized correlation coefficient' newline ...
'' newline ...
'persistent buffer_tx buffer_rx' newline ...
'bufferSize = 4096;' newline ...
'frameSize = length(tx_signal);' newline ...
'' newline ...
'% Initialize buffers' newline ...
'if isempty(buffer_tx)' newline ...
'    buffer_tx = zeros(bufferSize, 1);' newline ...
'    buffer_rx = zeros(bufferSize, 1);' newline ...
'end' newline ...
'' newline ...
'% Update circular buffers' newline ...
'buffer_tx = [buffer_tx(frameSize+1:end); tx_signal(:)];' newline ...
'buffer_rx = [buffer_rx(frameSize+1:end); rx_signal(:)];' newline ...
'' newline ...
'% Cross-correlation to find delay' newline ...
'maxLag = bufferSize/2;' newline ...
'[xcorr_result, lags] = xcorr(buffer_rx, buffer_tx, maxLag);' newline ...
'' newline ...
'% Find peak' newline ...
'[maxVal, maxIdx] = max(abs(xcorr_result));' newline ...
'delay_samples = lags(maxIdx);' newline ...
'' newline ...
'% Convert to milliseconds' newline ...
'latency_ms = double(delay_samples) / double(Fs) * 1000;' newline ...
'' newline ...
'% Normalized correlation' newline ...
'norm_tx = sqrt(sum(buffer_tx.^2));' newline ...
'norm_rx = sqrt(sum(buffer_rx.^2));' newline ...
'correlation = maxVal / (norm_tx * norm_rx + 1e-10);' newline ...
'end' newline];

% Save to file for reference
fid = fopen('latency_function_code.m', 'w');
fprintf(fid, '%s', latencyFcnCode);
fclose(fid);

%% Print Instructions
fprintf('\n');
fprintf('='.^60 + '\n');
fprintf('   MODEL CREATED: %s.slx\n', modelName);
fprintf('='.^60 + '\n');
fprintf('\n');
fprintf('REQUIRED MANUAL STEP:\n');
fprintf('--------------------\n');
fprintf('1. Double-click the "LatencyCalc" block in the model\n');
fprintf('2. Delete the default function code\n');
fprintf('3. Copy the code from "latency_function_code.m" and paste it\n');
fprintf('4. Click "Save and Close" (Ctrl+S)\n');
fprintf('\n');
fprintf('VERIFY AUDIO DEVICES:\n');
fprintf('--------------------\n');
fprintf('- Output: %s\n', outputDev);
fprintf('- Input:  %s\n', inputDev);
fprintf('\n');
fprintf('If devices are different, double-click AudioOut and AudioIn\n');
fprintf('blocks to change the device names.\n');
fprintf('\n');
fprintf('TO RUN:\n');
fprintf('-------\n');
fprintf('Click the green "Run" button or press Ctrl+T\n');
fprintf('\n');

%% Open the latency function code file
edit('latency_function_code.m');

fprintf('The latency function code has been opened in the editor.\n');
fprintf('Copy this code to the MATLAB Function block.\n');
